name: linting, testing, building
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build prod
        run: npm run build:prod
        if: always()
      - name: lint ts
        run: npm run lint:ts
        if: always()
      - name: lint scss
        run: npm run lint:scss
        if: always()
      - name: test unit
        run: npm run test:unit
        if: always()
      - name: storybook build
        run: npm run storybook:build
        if: always()