name: linting, testing, building
run-name: ${{ github.actor }}
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm install
      - name: build prod
        run: npm run build:prod
      - name: lint ts
        run: npm run lint:ts
      - name: lint scss
        run: npm run lint:scss
      - name: test unit
        run: npm run test:unit
      - name: storybook build
        run: npm run storybook:build
